import React from 'react'

export const About = () => {
    return (
        <section className="page">
            <header>
              <span className="section-label">About</span>
              <h2>Birthed in the 47th Year of the Hip Hop Era</h2>
              <div className="wallet-address">
                <span>UHHM.crypto Wallet address</span> <span>0x0451378B83aa6F8E978576F036bfd9c3C69683F9</span>
              </div>
            </header>
            <p>
                The Hip Hop Heads First Edition is a collaborative NFT art series featuring the work of the celebrated illustrator André LeRoy Davis, creator of The Source Magazine’s iconic The Last Word and the background animation of Ed Young, one of The Source Magazine’s original co-owners. Each illustration exists as a collection of 47 to represent the 47 Years of the Hip Hop Era. The animation loops at a rate of ~47.8 seconds to pinpoint the time of creation in the Hip Hop Era.
            </p>
            <p>
                Each Hip Hop Head First Edition is named in relation to the artist’s place in the Hip Hop Era. And each featured artist has earned a place in the history of Hip Hop that warranted an  illustration by André LeRoy Davis. Hip Hop Heads were featured in The Last Word because the artist was central to the musical, social, political, economic or lifestyle news of the moment and shaped the history of Hip Hop at a moment in time – to be illustrated as a Hip Hop Head meant that you were, and would always be, Historic.
                </p>
            <p>
                The #1 of each series is being donated to reside in and establish the Universal Hip Hop Museum’s original crypto art collection. The #38 - #47 of each series is being made available to the featured artist or the artist’s estate if they verify and claim their NFTsgift. Both the Artists/Artist’s Estate and the Universal Hip Hop Museum will share in the royalty streams for secondary market sales of #2 - #47 of each series. André LeRoy Davis and Ed Young are making these donations to show the unique power and potential of NFTs to benefit creatives and their estates in ways never before possible.
            </p>
            <p>
                The animation background code is generated by the most significant numbers in Hip Hop history with the sine waves and animation frame rates dependent upon these numbers creating the plasma-type flow illustrating the passage of the Hip Hop Era through these 47 years.
            </p>
            <h4 className="button" onClick={() => history.back()}>← Back</h4>
        </section>
    )
}